path: /blog/author/diego-wawrzeniak
tag: author
name: Diego Wawrzeniak
role: authors.0diego.rol
description: authors.0diego.description
bio: authors.0diego.description
pageName: authors.0diego.pageName
image: /images/authors/diego-wawrzeniak.png
from: Piracanga, Brasil
color: black
tabs:
  - {}
actionBar:
  buttons:
    - color: purple
  enabled: false
meta:
  robots: 'index, follow'
  twitter: {}
pagination: {}
