path: /blog/author/pablo-tutino
tag: author
name: Pablo Tutino
linkedin: https://www.linkedin.com/in/pablotutino/
github: https://github.com/dargonar
role: authors.1pablo.rol
description: authors.1pablo.description
bio: authors.1pablo.description
pageName: authors.1pablo.pageName
image: /images/authors/tuti.jpg
from: Buenos Aires, Argentina
color: black
tabs:
  - {}
actionBar:
  buttons:
    - color: purple
  enabled: false
meta:
  robots: 'index, follow'
  twitter: {}
pagination: {}
