path: /blog/author/barbara-leao
tag: author
name: Bárbara Leão
role: authors.2barbara.rol
description: authors.2barbara.description
bio: authors.2barbara.description
pageName: authors.2barbara.pageName
image: /images/authors/barbara-leao.png
from: Lisboa, Portugal
color: black
tabs:
  - {}
actionBar:
  buttons:
    - color: purple
  enabled: false
meta:
  robots: 'index, follow'
  twitter: {}
pagination: {}
