path: /blog/author/norton-toribio
tag: author
name: Norton Toribio
role: authors.3norton.rol
description: authors.3norton.description
bio: authors.3norton.description
pageName: authors.3norton.pageName
image: /images/authors/norton-toribio.png
from: Piracanga, Brasil
color: black
tabs:
  - {}
actionBar:
  buttons:
    - color: purple
  enabled: false
meta:
  robots: 'index, follow'
  twitter: {}
pagination: {}
