path: /blog/author/niv-sardi
tag: author
name: Niv Sardi
github: https://github.com/xaiki
role: authors.4niv.rol
description: authors.4niv.description
bio: authors.4niv.description
pageName: authors.4niv.pageName
image: /images/authors/niv-sardi.png
from: Neuquen, Argentina
color: black
tabs:
  - {}
actionBar:
  buttons:
    - color: purple
  enabled: false
meta:
  robots: 'index, follow'
  twitter: {}
pagination: {}
