path: /blog/author/robert-wallach
tag: author
title: Robert Wallach
subtitle: >-
  Editor-in-chief, contributing writer, and jack-of-all-trades at Stoplight.
  Earned an MFA at Emerson and has worked as a journalist, editor, and graphic
  designer for numerous publications and as a freelancer.
pageName: Content & Support
image: /images/wallach_headshot.png
color: blue
actionBar:
  enabled: false
meta:
  favicon: /images/mark_light_bg.png
  robots: 'index, follow'
  title: Robert Wallach | Stoplight
  twitter:
    title: Robert Wallach | Stoplight
    username: '@stoplightio'
pagination: {}
