path: /about
hero:
  particles: true
  subtitle: >-
    Con un equipo distribuido y multidiciplanario Cristal Network logra
    crear soluciones de alta tecnologia que pegan perfectamente a las
    necesidades de las comunidades en las cuales sus miembros vienen creando
    micro-revoluciones hace varios años.
  title: Acerca de Nosotros
businesses:
  quotes:
    - author: The Nice guy
      company: The EVil Company
      image:
        alt: EvilCorp
        src: /images/evil_logo.png
      quote: >-
        Having all the tools to model, test, and document our API in one place,
        and integrating it nicely along the entire CI/CD workflow process has
        been extremely helpful for us.
      role: Cloud Architect
  title: Los actores sociales aman a Cristal Network
pressSection:
  articles:
    - date: 'October, 2018'
      description: 'To Help Developers Get A Grip On APIs, Cristal Raises $3.25M'
      href: >-
        https://news.crunchbase.com/news/to-help-developers-get-a-grip-on-apis-stoplight-raises-3-25m
      image: /images/logo_crunchbase.png
      publication: crunchbase news
  cta:
    color: grey-darkest
    href: 'https://press.cristal.tk/company'
    name: More Press & Assets
  title: In The Press
# actionBar:
#   buttons:
#     - color: accent
#       href: 'https://angel.co/stoplight/jobs'
#       title: Learn More
#   enabled: true
#   text: Want to join the team? We're hiring!
