marketing:
  title: Nossa visao
  cards:
    - bgColor: blue
#      button:
#        href: /moeda-local
#        caption: 'Criar Moeda'
      icon:
        name: paint-brush
        style: solid
      title: 'Moeda Local'
      subtitle: 'Criar uma moeda local ficou fácil!'
      description: >-
         - Defina os critérios que serão aplicados em sua moeda social e que
         tipo de parâmetros serão utilizados no design monetário.

         - Coloque a moeda em circulação dentro de sua comunidade.
    - bgColor: orange
      # button:
      #   href: /banco-comunitario
      #   caption: 'Criar Banco Comunitário'
      icon:
        name: flask
        style: solid
      title: Banco Comunitário
      subtitle: 'Serviços bancários a sua comunidade'
      description: >-
         - Cristal é um sistema completo para bancos comunitários de desenvolvimento (BCDs).

         - Possibilita transferências entre contas de pessoas e negócios, facilitando as trocas e apoiando a economia local.
    - bgColor: green
      # button:
      #   href: /economia-local
      #   caption: 'Desenvolver Economia Local'
      icon:
        name: book
        style: solid
      title: 'Monitoreamento e Anàlises'
      subtitle: 'Acompanhe de perto a economia local'
      description: >-
         - Tenha informação em tempo real sobre o que está acontecendo na economia local.

         - Dashboard com indicadores, análises e ferramentas de apoio para o desenvolvimento local.
    - bgColor: grey-darkest
      # button:
      #   href: /signup
      #   caption: 'Comence Agora'
      icon:
        name: server
        style: solid
      title: 'Sólida, Transparente e Segura'
      subtitle: 'Segurança de Nível Bancário'
      description: >-
        Usando a tecnologia Blockchain, oferecemos um registro seguro e imutável a todas as transações.
        Tornando Cristal um sistema mais seguro e estável do que de muitos bancos grandes por aí.
hero:
  subtitle: >-
    Em minutos você cria uma **moeda social**, configura um **banco
    communitário** e comença a fortalecer uma **nova economia** no local onde você mora.
  title: Desenvolva a Economia Local de Sua Comunidade
collage:
  images:
    - alt: Banco Palmas
      src: /images/partenairs/wb_banco_palmas.png
    - alt: Biovilla
      src: /images/partenairs/wb_biovilla.png
    - alt: Banco Inkiri
      src: /images/partenairs/wb_inkiri-logo.png
    - alt: Butter Project
      src: /images/partenairs/wb_popcorn-time-icon-png-4.png
    - alt: Waba Network
      src: /images/partenairs/wb_waba.png
  title: Quem nos apóia
  subtitle: >-
    Cristal Network é uma iniciativa comunitária, apoiada por
    diversas pessoas e ogranizaçôes, entre elas:
panesCallout:
  title: Nossa Rede e sua rede
  cta:
    href: 'https://next.cristal.tk/'
    name: Quem somos ?
  left: >-
    Cristal Network é uma plataforma online, criada para empoderar bancos
    comunitários, de desenvolvimento local. Baseada em Blockchain garante um
    novo patamar de segurança e confiabilidade aos bancos locais. Ampliando
    ainda mais o impacto social gerado por estas organizações.
  right: >-
    Atualmente existem milhares de bancos comunitários e moedas locais
    espalhadas pelo mundo. Por meio de tecnologia buscamos fortalecer e
    conectar este movimento, ajudando comunidades a cuidarem de sua própria
    economia local.
  image: /images/home-hero.png
