meta:
  description: >-
    Todo lo que necesita saber sobre Cristal Network y sus hackers del demonio
    team; united in their passion for creating best in class API tooling.
  favicon: /images/mark_light_bg.png
  title: Acerca de nosotres | Cristal Network
  twitter:
    title: Siganos | Cristal Network
    username: '@cristalnetwork'
