banners: []
info:
  address:
    addressLocality: Piracanga
    addressRegion: BR
    alternateName: Cristal Network
    description: >-
      Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    email: hello@stoplight.io
    name: Stoplight.io
    postalCode: '78704'
    streetAddress: 1100 S 1st St
  email: sales@stoplight.io
header:
  title: Cristal **Network**
  items:
    - href: /quem-somos/
      title: Quem Somos?
    - href: /roadmap/
      title: Roadmap
    - href: 'https://inkiri.cristalnetwork.org'
      isButton: true
      title: Demo
actionBar:
  buttons:
    - color: purple
      href: /demo
      outlined: true
      title: Request a Demo
    - color: purple
      href: 'https://next.stoplight.io'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - title: Product Discovery
      links:
        # - href: https://github.com/cristalnetwork/inkiri-frontend
        #   title: Frontend Source Code
        # - href: https://github.com/cristalnetwork/inkiri-backend
        #   title: Backend Source Code
        # - href: https://github.com/cristalnetwork/inkiri-eos-contracts
        #   title: Smart Contracts
        # - href: https://github.com/cristalnetwork
        #   title: Github
        - href: https://whimsical.com/9kXXrEa6LzuJtRroPsihpa
          title: Tech Architecture
        - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-(mine)?node-id=147%3A4464&scaling=min-zoom
          title: Bank Administrator @ Figma
        - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-(mine)?node-id=580%3A160&scaling=min-zoom
          title: Personal Account @ Figma
        - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-mine?node-id=472%3A9248&scaling=min-zoom
          title: Personal Account Mobile @ Figma
        - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-(mine)?node-id=627%3A0&scaling=min-zoom
          title: Business/Fundo Account @ Figma
    - title: Organization
      links:
        - href: /quem-somos/
          title: Quem Somos?
        - href: /roadmap/
          title: Roadmap
        # - href: /contact-us/
        #   title: Contact Us
    - title: Supporters
      links:
        - href: https://www.biovilla.org/
          title: Biovilla
        - href: https://www.institutobancopalmas.org/
          title: Banco Palmas
        - href: https://portal.fgv.br/en
          title: Fundação Getúlio Vargas
        - href: https://ufrj.br/
          # title: Universidade Federal do Rio de Janeiro
          title: UFRJ
        - href: https://piracanga.com/
          title: Instituto inkiri
        - href: http://butterproject.org/
          title: Butter Project
        - href: https://waba.network
          title: Waba.Network
  legal:
    - href: /privacy/
      title: Privacy
    - href: /terms/
      title: Terms of Use
    - href: /policy/
      title: Policy
  social:
    - href: 'https://twitter.com/networkcristal'
      icon:
        - fab
        - twitter
    - href: 'https://www.linkedin.com/company/cristalnetwork'
      icon:
        - fab
        - linkedin
    - href: 'https://www.github.com/cristalnetwork'
      icon:
        - fab
        - github
meta:
  description: Economia Cristalina | Cristal Network
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  robots: 'index, follow'
  title: Cristal Network
  twitter:
    description: The Complete API Toolkit for Teams and Enterprise | Stoplight
    image: /images/home-hero.png
    title: Cristal Network
    username: '@stoplightio'
  url: 'https://stoplight.io'
integrations:
  googleTagManager: GTM-58LWL5P
  hubspot: 4892910
  intercom: g7eo4oae
