banners: []
info:
  address:
    addressLocality: info.address.addressLocality
    addressRegion: info.address.addressRegion
    alternateName: info.address.alternateName
    description: info.address.description
    email: hello@cristalnetwork.org
    name: CristalNetwork.org
    postalCode: info.address.postalCode
    streetAddress: info.address.streetAddress
  email: hello@cristalnetwork.org
header:
  title: Cristal **Network**
  show_languages: true
  items:
    - href: /team/
      title: header.team
    - href: /roadmap/
      title: header.roadmap
    - href: 'https://demo.cristalnetwork.org'
      isButton: true
      title: header.demo
    # - href: #
    #   width: 200
    #   icon:
    #     - fas
    #     - language
    #   links: 
    #     - href:  /en/
    #       title: 'header.languages.en'
    #     - href:  /pt/
    #       title: 'header.languages.pt'
    #     - href:  /es/
    #       title: 'header.languages.es'
footer:
  columns:
    - title: footer.source_code
      links:
        - href: https://github.com/cristalnetwork/inkiri-frontend
          title: footer.frontend
        - href: https://github.com/cristalnetwork/inkiri-backend
          title: footer.backend
        - href: https://github.com/cristalnetwork/inkiri-eos-contracts
          title: footer.smart_contracts
        - href: https://github.com/cristalnetwork
          title: footer.organization_repo
        - href: https://whimsical.com/9kXXrEa6LzuJtRroPsihpa
          title: footer.tech_architecture
        # - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-(mine)?node-id=147%3A4464&scaling=min-zoom
        #   title: Bank Administrator @ Figma
        # - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-(mine)?node-id=580%3A160&scaling=min-zoom
        #   title: Personal Account @ Figma
        # - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-mine?node-id=472%3A9248&scaling=min-zoom
        #   title: Personal Account Mobile @ Figma
        # - href: https://www.figma.com/proto/wesbb4BGHRSwTIFdqpbyFT/inkiri-dise%C3%B1o-v1-(mine)?node-id=627%3A0&scaling=min-zoom
        #   title: Business/Fundo Account @ Figma
    - title: footer.organizatione
      links:
        - href: /team/
          title: footer.team
        - href: /roadmap/
          title: footer.roadmap
        - href: /contact-us/
          title: footer.contact_us
    - title: footer.supporters
      links:
        - href:  https://www.biovilla.org/
          title: footer.supporters.biovilla
        - href:  https://www.institutobancopalmas.org/
          title: footer.supporters.banco_palmas
        - href:  https://portal.fgv.br/en
          title: footer.supporters.fgv
        - href:  https://ufrj.br/
          title: footer.supporters.ufrj
        - href:  https://piracanga.com/
          title: footer.supporters.instituto_inkiri
        - href:  http://butterproject.org/
          title: footer.supporters.butter_project
        - href:  https://waba.network
          title: footer.supporters.waba_network
  # legal:
  #   - href: /privacy/
  #     title: Privacy
  #   - href: /terms/
  #     title: Terms of Use
  #   - href: /policy/
  #     title: Policy
  social:
    # - href: 'https://twitter.com/networkcristal'
    #   icon:
    #     - fab
    #     - twitter
    # - href: 'https://www.linkedin.com/company/cristalnetwork'
    #   icon:
    #     - fab
    #     - linkedin
    - href: 'https://www.github.com/cristalnetwork'
      icon:
        - fab
        - github
meta:
  description: meta.description
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  robots: 'index, follow'
  title: meta.title
  twitter:
    description: Cristal Network
    image: /images/home-hero.png
    title: Cristal Network
    username: '@cristalnetwork'
  url: 'https://cristalnetwork.org'
integrations:
  googleTagManager: xx
  hubspot: xx
  intercom: xx
