banners: []
info:
  address:
    addressLocality: Piracanga
    addressRegion: BR
    alternateName: Cristal Network
    description: >-
      Stoplight, providing engineering teams with the best way to document,
      test, and build web APIs.
    email: hello@stoplight.io
    name: Stoplight.io
    postalCode: '78704'
    streetAddress: 1100 S 1st St
  email: sales@stoplight.io
header:
  title: Cristal **Network**
  items:
    - href: /product_roadmap/
      title: Product and Roadmap
    - href: /case-studies/
      title: Case Studies
    - href: /about/
      icon:
        - fas
        - users
      title: About Us
    - href: /demo/
      isButton: true
      title: Request Demo
actionBar:
  buttons:
    - color: purple
      href: /demo
      outlined: true
      title: Request a Demo
    - color: purple
      href: 'https://next.stoplight.io'
      title: Create a Free Account
  enabled: false
  text: Getting started is easy. Be up and running in minutes.
footer:
  columns:
    - title: Products
      links:
        - href: /design/
          title: Design
        - href: /mocking/
          title: Mocking
    - title: Organization
      links:
        - href: /about/
          title: About Us
        - href: /case-studies/
          title: Case Studies
        - href: /contact-us/
          title: Contact Us
    - title: Supporters
      links:
        - href: https://piracanga.com/instituto-inkiri/
          title: Inkiri
        - href: https://institutobancopalmas.org
          title: Banco Palmas
        - href: https://www.biovilla.org/
          title: BioVilla
        - href: https://waba.network/
          title: Waba
  legal:
    - href: /privacy/
      title: Privacy
    - href: /terms/
      title: Terms of Use
    - href: /policy/
      title: Policy
  social:
    - href: 'https://twitter.com/networkcristal'
      icon:
        - fab
        - twitter
    - href: 'https://www.linkedin.com/company/cristalnetwork'
      icon:
        - fab
        - linkedin
    - href: 'https://www.github.com/cristalnetwork'
      icon:
        - fab
        - github
meta:
  description: Economia Cristalina | Cristal Network
  favicon: /favicons/favicon.ico
  image: /images/home-hero.png
  robots: 'index, follow'
  title: Cristal Network
  twitter:
    description: The Complete API Toolkit for Teams and Enterprise | Stoplight
    image: /images/home-hero.png
    title: Cristal Network
    username: '@stoplightio'
  url: 'https://stoplight.io'
integrations:
  googleTagManager: GTM-58LWL5P
  hubspot: 4892910
  intercom: g7eo4oae
